let set1 = new Set([1,2,3,4,5,2,2,2,9,3])
console.log(set1)
console.log(set1.size)
set1.add(10)
console.log(set1)
console.log(set1.size)
set1.delete(10)
console.log(set1)
console.log(set1.size)

let set2 = new Set("viikassssssharrrmmma")
console.log(set2)
console.log(set2.size)
set2.clear()
console.log(set2)
console.log(set2.size)